
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "DINHEIRO LISTAR MOEDA PRODUTO SAIR SALDO SELECIONARmoed : MOEDA moeds '.'moeds : DINHEIRO moedslmoedsl : ',' DINHEIRO moedslmoedsl : "
    
_lr_action_items = {'MOEDA':([0,],[2,]),'$end':([1,5,],[0,-1,]),'DINHEIRO':([2,7,],[4,8,]),'.':([3,4,6,8,9,],[5,-4,-2,-4,-3,]),',':([4,8,],[7,7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'moed':([0,],[1,]),'moeds':([2,],[3,]),'moedsl':([4,8,],[6,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> moed","S'",1,None,None,None),
  ('moed -> MOEDA moeds .','moed',3,'p_moed','main.py',49),
  ('moeds -> DINHEIRO moedsl','moeds',2,'p_moeds','main.py',61),
  ('moedsl -> , DINHEIRO moedsl','moedsl',3,'p_moedsl','main.py',65),
  ('moedsl -> <empty>','moedsl',0,'p_moeds_vazio','main.py',69),
]
